### ISSUE TITLE
How to download the NuInstruct datasets?

### ISSUE THREAD

**Issue by dszpr** [xmed-lab/NuInstruct#2]
Hi! Much appreciated for the excellent work!
Is the NuInstruct datasets open source? How to download the NuInstruct datasets?

**Comment by Scipio1996** [comment]
Thanks for paying attention to our work, we will provide a download link if accepted.

**Comment by adam-coogan-vw** [comment]
Hello! Are you still planning to provide a download link? Have you decided how you will license the data?

**Comment by Scipio1996** [comment]
> Hello! Are you still planning to provide a download link? Have you decided how you will license the data?

Hi, We have uploaded the dataset annotations in  [Annoatations](https://github.com/xmed-lab/NuInstruct/tree/master/annotations), and you can download the images from [nuScenes](https://www.nuscenes.org/)

**Comment by adam-coogan-vw** [comment]
Thanks! What license are you releasing your annotations under?
