### ISSUE TITLE
other storage solutions for annotations

### ISSUE THREAD

**Issue by annopackage** [xmed-lab/NuInstruct#5]
Hi, thanks for your great work and sharing data. Downloading the training annotation is failed due to data quota and bandwidth, would you mind sharing the data through other solutions, such google-drive?

**Comment by Scipio1996** [comment]
> Hi, thanks for your great work and sharing data. Downloading the training annotation is failed due to data quota and bandwidth, would you mind sharing the data through other solutions, such google-drive?

Hi, Have upload the annotations in google drive: https://drive.google.com/file/d/1ybwvgnPFRVwmEAJudWwnGQ8wLitzQ82O/view?usp=sharing
